name: getxapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  lottie: ^2.1.0
  flutter_svg:
  url_launcher:
  shared_preferences:
  dio:

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

